service: notes-api
provider:
  name: aws
  runtime: nodejs6.10
  profile: infrontlabs
  stage: dev
  region: us-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
functions:
  create:
    handler: notes/create.handler
    events:
      - http:
          path: notes
          method: post
          cors: true
  list:
    handler: notes/list.handler
    events:
      - http:
          path: notes
          method: get
          cors: true
  get:
    handler: notes/get.handler
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
  update:
    handler: notes/update.handler
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
  delete:
    handler: notes/delete.handler
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
